config/routes.rb
Rails.application.routes.draw do
  get "upload" => "images#new", :as => "upload"
  get 'images/index'
  get 'images/new'
  get 'images/create'
  get 'images/destroy'
  get 'categories/index'
  get 'categories/show'
  get 'categories/new'
  get 'categories/edit'
  get 'categories/create'
  get 'categories/update'
  get 'categories/destroy'
  resources :images, :categories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'images#index'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :images
end

app/models/image.rb
class Image < ApplicationRecord
    belongs_to :category

    mount_uploader :image, ImageUploader
    before_save :update_image_attributes

    private
    def update_image_attributes
        if image.present? && image_changed?
            self.image_content_type = image.file.content_type
            self.image_file_size = image.file.size
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
        before_action :getCategoryNav
    private
    def getCategoryNav
        @categoryNav = Category.all
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
  end

  def show
    @category = Category.find(params[:id])
    @category = Category.all
    @images = @category.img
  end

  def new
    @category = Category.new
  end

  def edit
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      flash[:notice] = "Category Created"

      redirect_to root_path
    else
      render 'new'
    end

  end

  def update
  end

  def destroy
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def index
    @images = Image.all
    @categories = Category.all
  end

  def new
    @image = Image.new
  end

  def create
    @image = Image.new(image_params)

    if @image.save
      flash[:notice] = "Image Uploaded"

      redirect_to root_path
    else
      render 'new'
    end
  end

  def destroy
  end

  private
  def image_params
    params.require(:image).permit(:image, :category_id, :image_title, :image_description,
      :image_file_size, :image_content_type, :remote_image_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/categories/create.html.erb
<h1>Categories#create</h1>
<p>Find me in app/views/categories/create.html.erb</p>

app/views/categories/destroy.html.erb
<h1>Categories#destroy</h1>
<p>Find me in app/views/categories/destroy.html.erb</p>

app/views/categories/edit.html.erb
<h2> Edit Category</h2>
<%= form_for  @category do |f|%>
  <!-- check for errors -->
    <% if @category.errors.any? %>
      <% @category.errors.full_messages.each do |msg| %>
        <!--Show errors -->
        <div class="alert alert-danger"><%= msg %></div>
      <% end %>
    <% end %>
    <div class="form-group">
      <%= f.label :name %><br />
      <%= f.text_field :name, class:'form-control'%><br />
    </div>
    <%= f.submit "Submit", class: 'btn btn-primary'%>
    <%=link_to "Cancel", categories_path, class:'btn btn-default'%>
<% end %>

<h3 class="page-header">Images in<%= @category.name %></h3>
<div id="edit_images">
  <% if @images.exists? %>
    <% @images.each_slice(6) do |image| %>
      <div class="row">
        <% image.each do |image| %>
          <div class="col-md-2">
            <%= image_tag image.image_url(:thumb) %>
            <center><%= link_to "Delete", image_path(image), class:'delete', method: :delete, data: {confirm: 'Are you sure?'}%></center>
          </div>
        <% end %>
      <% end %>
    </div>
    <% end %>

app/views/categories/index.html.erb
<h1>Categories#index</h1>
<p>Find me in app/views/categories/index.html.erb</p>

app/views/categories/new.html.erb
<h2> Add New Category</h2>
<%= form_for  @category do |f|%>
  <!-- check for errors -->
    <% if @category.errors.any? %>
      <% @category.errors.full_messages.each do |msg| %>
        <!--Show errors -->
        <div class="alert alert-danger"><%= msg %></div>
      <% end %>
    <% end %>
    <div class="form-group">
      <%= f.label :name %><br />
      <%= f.text_field :name, class:'form-control'%><br />
    </div>
    <%= f.submit "Submit", class: 'btn btn-primary'%>
    <%=link_to "Cancel", categories_path, class:'btn btn-default'%>
<% end %>

app/views/categories/show.html.erb
<div id="gallery">
<h2><%= @category.name%></h2>
  <% if @images.exists? %>
    <% @images.each_slice(4) do |image| %>
     <div class = "row">
      <% image.each do |image| %>
        <div class="col-mid-3">
        <div class="photo photo-type-line">
        <a href="<%= image.image_url() %>" class="photo-hover" data-lightbox="my-images"
         data-title="<% image.image_title %>">
         <div class="photo-info">
         <div class="headline"><%= image.image_title %></div>
         <div class="line"></div>
         <div class="desc"><%= image.image_description %></div>
      </div>
      <div class="mask"></div>
      </a>
      <div class="photo-img"><%= image_tag image.image_url(:thumb) %>
      </div>
      </div>
      <% end %>
      </div>
      <% end %>
      <% else %> <p>There are no images</p>
      <% end %>
</div>

app/views/categories/update.html.erb
<h1>Categories#update</h1>
<p>Find me in app/views/categories/update.html.erb</p>

app/views/images/create.html.erb
<h1>Images#create</h1>
<p>Find me in app/views/images/create.html.erb</p>

app/views/images/destroy.html.erb
<h1>Images#destroy</h1>
<p>Find me in app/views/images/destroy.html.erb</p>

app/views/images/index.html.erb
<div id="gallery">
<h2>All Images</h2>
  <% if @images.exists? %>
    <% @images.each_slice(4) do |image| %>
     <div class = "row">
      <% image.each do |image| %>
        <div class="col-mid-3">
        <div class="photo photo-type-line">
        <a href="<%= image.image_url() %>" class="photo-hover" data-lightbox="my-images"
         data-title="<% image.image_title %>">
         <div class="photo-info">
         <div class="headline"><%= image.image_title %></div>
         <div class="line"></div>
         <div class="desc"><%= image.image_description %></div>
      </div>
      <div class="mask"></div>
      </a>
      <div class="photo-img"><%= image_tag image.image_url(:thumb) %>
      </div>
      </div>
      <% end %>
      </div>
      <% end %>
      <% else %> <p>There are no images</p>
      <% end %>
</div>

app/views/images/new.html.erb
<h2>Upload Image</h2>

<%= form_for @image, :html => { :multipart => true } do |f| %>
   <!--check for errors-->
    <% if @image.errors.any? %>
      <% @image.errors.full_messages.each do |msg| %>
      <!--Show errors -->
        <div class= "alert alert-danger"><%= msg %></div>
      <% end %>
    <% end %>

	<div class = "from-group">
	  <%= f.label :image_title %>
	  <%= f.text_field :image_title ,class: 'form-control'%>
	</div>

	<div class = "from-group">
	  <%= f.label :category %>
      <%= f.select :category_id,Category.all.collect {|x| [x.name, x.id]},
       {:include_blank => 'select one'} ,class: 'form-control'%>
	</div>

	<div class = "from-group">
	  <%= f.label :image_description %>
	  <%= f.text_area :image_description, class: 'form-control' %>
	</div>

    <div class="form-control">
      <%= f.label :image %>
      <%= f.file_field :image %>
    </div>

	<%= f.submit "submit", class:'btn btn-primary' %>
	<%= link_to "cancel", images_path, class:'btn btn-default' %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RGallery</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <!--==============================
              header
=================================-->
<header>
<!--==============================
            Stuck menu
=================================-->
  <section id="stuck_container">
    <div class="container">
      <div class="row">
        <div class="grid_12">

            <h1>
              <a href="index.html">
                <img src="images/logo.png" alt="Image Gallery">
              </a>
            </h1>

          <div class="navigation ">
            <nav>
            <div id="navbar" class="collapse navbar-collapse">
              <ul class="sf-menu"class="nav navbar-nav pull-left">

               <li class="current"><%= link_to "Home", root_path %></li>
               <% @categoryNav.each do |category|%>
                <li><%= link_to category.name, category_path(category.id) %></li>
               <% end %>
              </ul>
            </div>
            <ul  class="nav navbar-nav pull-right">
            <li><%= link_to "Upload Photo", upload_path %></li>
            <li><%= link_to "Add Category", new_category_path %></li>
            </ul>
            </nav>
            <div class="clear"></div>
          </div>
        </div>
      </div>
    </div>
  </section>
</header>

<section>
  <div class="container">
    <h2>All Images</h2>
  </div>
</section>

<!--=====================
          Content
======================-->
<section class="content gallery pad1"><div class="ic">More Website Templates @ TemplateMonster.com - July 30, 2014!</div>
  <div class="container">
  <% if flash[:notice] %>
    <div class="alert alert-success"><%= flash[:notice] %></div>
  <% end %>

  <% if flash[:alert] %>
    <div class="alert alert-danger"><%= flash[:notice] %></div>
  <% end %>
     <%= yield %>
  </div>
</section>
<!--==============================
              footer
=================================-->
<footer id="footer">
  <div class="container">
    <div class="row">
      <div class="grid_12">
        <div class="socials">
          <a href="#" class="fa fa-twitter"></a>
          <a href="#" class="fa fa-facebook"></a>
          <a href="#" class="fa fa-google-plus"></a>
          <a href="#" class="fa fa-pinterest"></a>
        </div>
        <div class="copyright"><span class="brand">Bliss </span> &copy; <span id="copyright-year"></span> | <a href="#">Privacy Policy</a> <div>Website designed by <a href="http://www.templatemonster.com/" rel="nofollow">TemplateMonster.com</a></div>
        </div>
      </div>
    </div>
  </div>
</footer>
  </body>
</html>